export const properties = [
  {
    id: 1,
    name: "Luxury Villa",
    location: "New York",
    price: 5000,
    type: "Villa",
    available: true,
    image: "https://tse2.mm.bing.net/th?id=OIP.fFF3Uo8Gp2ROms2DO3nbxwHaEK&pid=Api&P=0&h=180",
  },
  {
    id: 2,
    name: "Cozy Apartment",
    location: "Los Angeles",
    price: 2000,
    type: "Apartment",
    available: false,
    image: "https://tse4.mm.bing.net/th?id=OIP.cM7nac_VqMgQMD7NOpxoDAHaE8&pid=Api&P=0&h=180",
  },
  {
    id: 3,
    name: "Modern House",
    location: "Chicago",
    price: 3500,
    type: "House",
    available: true,
    image: "https://tse1.mm.bing.net/th?id=OIP.kINwqVgvCEYzGUOcI2RKCgHaE8&pid=Api&P=0&h=180",
  },
  {
    id: 4,
    name: "Beachfront Condo",
    location: "Miami",
    price: 4500,
    type: "Condo",
    available: true,
    image: "https://tse3.mm.bing.net/th?id=OIP.CLWyboX7Pi1sgB_2nxhgYgHaEK&pid=Api&P=0&h=180",
  },
  {
    id: 5,
    name: "Penthouse Suite",
    location: "San Francisco",
    price: 8000,
    type: "Penthouse",
    available: false,
    image: "https://tse2.mm.bing.net/th?id=OIP.yxXxLWFvEuXHyksNkpwNoQHaER&pid=Api&P=0&h=180",
  },
  {
    id: 6,
    name: "Suburban Home",
    location: "Dallas",
    price: 3000,
    type: "House",
    available: true,
    image: "https://tse4.mm.bing.net/th?id=OIP.Zb_ERLrX2yCURk5elMIl8QHaE8&pid=Api&P=0&h=180",
  },
  {
    id: 7,
    name: "City Loft",
    location: "Seattle",
    price: 2500,
    type: "Loft",
    available: false,
    image: "https://tse2.mm.bing.net/th?id=OIP.AHWVFwGTAHxKOxY1TrUWSwHaEF&pid=Api&P=0&h=180",
  },
  {
    id: 8,
    name: "Rustic Cabin",
    location: "Denver",
    price: 2200,
    type: "Cabin",
    available: true,
    image: "https://tse3.mm.bing.net/th?id=OIP.D-LsL_l95q--mV46jUMkUwHaE8&pid=Api&P=0&h=180",
  },
  {
    id: 9,
    name: "Skyscraper Suite",
    location: "New York",
    price: 10000,
    type: "Suite",
    available: true,
    image: "https://tse1.mm.bing.net/th?id=OIP.Yfi939414hY-h8GL3JOJbAHaE8&pid=Api&P=0&h=180",
  },
  {
    id: 10,
    name: "Lakehouse Retreat",
    location: "Minnesota",
    price: 4000,
    type: "Lakehouse",
    available: false,
    image: "https://tse4.mm.bing.net/th?id=OIP.HS3bY1a22K9-l6OtlSvBYwHaD2&pid=Api&P=0&h=180",
  },
  {
    id: 11,
    name: "Countryside Cottage",
    location: "Nashville",
    price: 1800,
    type: "Cottage",
    available: true,
    image: "https://tse1.mm.bing.net/th?id=OIP.b_1recShkcZK_xhQ5qFPdgHaF6&pid=Api&P=0&h=180",
  },
  {
    id: 12,
    name: "Luxury Penthouse",
    location: "Las Vegas",
    price: 9500,
    type: "Penthouse",
    available: true,
    image: "https://tse4.mm.bing.net/th?id=OIP.-8QM1zIqkLRHKriqO9ceDwHaE8&pid=Api&P=0&h=180",
  },
  {
    id: 13,
    name: "Eco-Friendly Home",
    location: "Portland",
    price: 3200,
    type: "House",
    available: false,
    image: "https://tse3.mm.bing.net/th?id=OIP.8FXqBUY1c9iDK0iE4hNPrQHaEK&pid=Api&P=0&h=180",
  },
  {
    id: 14,
    name: "Urban Apartment",
    location: "Boston",
    price: 2700,
    type: "Apartment",
    available: true,
    image: "https://tse2.mm.bing.net/th?id=OIP.iXnqN7nxPZqGY3Syeb7ecQHaCU&pid=Api&P=0&h=180",
  },
  {
    id: 15,
    name: "Hillside Villa",
    location: "San Diego",
    price: 5500,
    type: "Villa",
    available: true,
    image: "https://tse1.mm.bing.net/th?id=OIP.v867ClgHgWzPEFXu-lwOigHaE8&pid=Api&P=0&h=180",
  },
  {
    id: 16,
    name: "High-rise Condo",
    location: "Houston",
    price: 4800,
    type: "Condo",
    available: false,
    image: "https://tse2.mm.bing.net/th?id=OIP.4NKS8F7lEoCnOfh4FJXxfAHaE7&pid=Api&P=0&h=180",
  },
  {
    id: 17,
    name: "Sunny Townhouse",
    location: "Phoenix",
    price: 3100,
    type: "Townhouse",
    available: true,
    image: "https://tse1.mm.bing.net/th?id=OIP.gmyyyoVSglcjZQuyTEwsogHaFj&pid=Api&P=0&h=180",
  },
  {
    id: 18,
    name: "Ski Resort Lodge",
    location: "Aspen",
    price: 7300,
    type: "Lodge",
    available: false,
    image: "https://tse4.mm.bing.net/th?id=OIP.rg7biBLfNcBoa2EcDKNNhwHaFj&pid=Api&P=0&h=180",
  },
  {
    id: 19,
    name: "Downtown Loft",
    location: "Chicago",
    price: 2900,
    type: "Loft",
    available: true,
    image: "https://tse3.mm.bing.net/th?id=OIP.PBjifBQCemWJy6cF-28-8AHaES&pid=Api&P=0&h=180",
  },
  {
    id: 20,
    name: "Mansion Estate",
    location: "Beverly Hills",
    price: 15000,
    type: "Mansion",
    available: true,
    image: "https://tse3.mm.bing.net/th?id=OIP.3KvBxVF7T9s6FA5BLK1pqQHaFj&pid=Api&P=0&h=180",
  },
  {
    id: 21,
    name: "Lakehouse Retreat",
    location: "Minnesota",
    price: 8000,
    type: "Lakehouse",
    available: false,
    image: "https://tse2.mm.bing.net/th?id=OIP.fFF3Uo8Gp2ROms2DO3nbxwHaEK&pid=Api&P=0&h=180",
  },

];
